language: rust
rust:
  - stable
  # - beta
  # - nightly
cache: cargo
before_script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo install clippy --force) fi
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo install rustfmt-nightly --force) fi
  - sudo apt-get update && sudo apt-get install imagemagick poppler-utils
script:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo clippy) fi
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo fmt -- --write-mode=diff) fi
  - cargo build
  - cargo test
