language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - (cargo install rustfmt || true)
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo install clippy --force) fi
script:
  - cargo fmt -- --write-mode=diff
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then (cargo clippy) fi
  - cargo build
  - cargo test
