[package]
name = "papers"
version = "0.2.3"
authors = [
    "Peter Gundel <peter.gundel@store2be.com",
    "Fausto Núñez Alberro <fausto.nunez@store2be.com>",
    "Tom Houlé <tom.houle@store2be.com>",
]

[dependencies]
chrono = "*"
dotenv = "*"
error-chain = "^0.11.0"
futures = "*"
futures-cpupool = "*"
log = "*"
mktemp = "*"
lazy_static = "*"
mime = "*"
quickcheck = "*"
hyper = "^0.11"
hyper-tls = "*"
regex = "*"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
sloggers = "^0.2"
rand = "*"
rusoto_core = { git = "https://github.com/store2be/rusoto", branch = "presigned-url" }
rusoto_s3 = { git = "https://github.com/store2be/rusoto", branch = "presigned-url" }
structopt = "0.1.6"
structopt-derive = "0.1.0"
tar = "*"
tera = "^0.10"
tokio-core = "*"
tokio-io = "*"
tokio-process = "*"

[dependencies.slog]
version = "^2"
features = ["max_level_debug", "release_max_level_debug"]
