[package]
name = "pape"
version = "0.1.0"
authors = [
    "Peter Gundel <peter.gundel@store2be.com",
    "Fausto Núñez Alberro <fausto.nunez@store2be.com>",
    "Tom Houlé <tom.houle@store2be.com>",
]

[dependencies]
futures = "*"
mktemp = "*"
hyper = { git = "https://github.com/hyperium/hyper" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tera = "*"
tokio-core = "*"
tokio-io = "*"
tokio-process = "*"
tokio-service = "*"

[[bin]]
name = "pape-server"
path = "./src/server.rs"
